
# should throw error since no main

fun foo() int {
    return 0;
}